version: '3'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    platform: linux/amd64
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./docker/wordpress/html:/var/www/html
      - ./docker/wordpress/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - db

  metasploit:
    image: metasploitframework/metasploit-framework:latest
    command: "./msfrpcd -a 0.0.0.0 -p 55553 -U msf -P password -S -f"
    ports:
      - "55553:55553"

  metasploit-mcp:
    build:
      context: .
      dockerfile: ./docker/metasploit-mcp/Dockerfile
    ports:
      - "8085:8085"
    extra_hosts:
      - "host.docker.internal:host-gateway"
