[tools]
node = "latest"
python = "3.13.3"
pipx = "1.7.1"
pdm = "2.24.1"

[env]
GOOGLE_GENAI_USE_VERTEXAI = "FALSE"

# .env には、git 管理したくない情報を記載する。
mise.file = ".env"

[tasks.run-cli]
description = "Run app as CLI"
run = [
    "pdm run adk run src",
]

[tasks.run-webui]
description = "Run app as WebUI"
run = [
    "pdm run adk web",
]

[tasks.code-format]
description = "Format code"
run = [
    "pdm run format",
]

[tasks.code-lint]
description = "Lint code"
run = [
    "pdm run lint",
]
