[tools]
python = "3.13.3"

[env]
GOOGLE_GENAI_USE_VERTEXAI = "FALSE"

# .env には、git 管理したくない情報を記載する。
mise.file = ".env"

[tasks.run-cli]
description = "Run app as CLI"
run = [
    "pdm run adk run src",
]

[tasks.run-webui]
description = "Run app as WebUI"
run = [
    "pdm run adk web",
]
